# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0003_auto_20170926_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='discuss.Category'),
        ),
    ]
